### ISSUE TITLE
WebView2 process crash with version prior to 118.0.2088.76 on Windows

### ISSUE THREAD

**Issue by SuperDumbTM** [wailsapp/go-webview2#24]
Duplicate the issue (https://github.com/wailsapp/wails/issues/3913) here for tracking.

**Summary**

An error message "The WebView2 process crashed and the application needs to be restarted" will show up when the GUI window is being "refocused" (mouse click on somewhere else and then click the app's window).

The incompatible versions seem to be `117.0.2045.60` and prior for `Wails v2.9.2`.

**Comment by SuperDumbTM** [comment]
I have tested that invoking `WindowMinimise` and then `WindowUnminimise` can trigger this error.

Combining with [Github release API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28), one can simply pull all the WebView2 binary from [WebView2RuntimeArchive](https://github.com/westinyang/WebView2RuntimeArchive/releases) and test whether an app will crash against each version.

If WebView2 error occurs, an error "ERR | WebVie2wProcess failed with kind 0" will appear.
![image](https://github.com/user-attachments/assets/a53030bf-2765-4474-a222-9751a44bbeac)

But I'm not sure how to gather the piece above into an automated test.

**Comment by xiexul** [comment]
I tested the borderless application and implemented a custom toolbar that crashes when zooming in, out, or closing(Quit). When dragging the window position, it also crashes. It seems that whenever the runtime is called, a crash exception occurs:”The WebView2 processcrashed and the application needs to be restarted“
![image](https://github.com/user-attachments/assets/ed2cba5f-0c1e-4e64-91b2-21e4b2c7e600)
![image](https://github.com/user-attachments/assets/a6ba0666-a2a3-4b25-8093-c5be5301c05f)


But when I drag using the native title bar, this exception does not occur


The incompatible versions seem to be 113.0.1774.50 and prior for Wails v2.9.2.

**Comment by leaanthony** [comment]
Have you tried using `replace` to downgrade the go-webview2 version ?

**Comment by xiexul** [comment]
> Have you tried using `replace` to downgrade the go-webview2 version ?

I tested downgrading go-webview2 to `1.0.13` and working fine, and getting higher than `1.0.13` was wiped out

**Comment by leaanthony** [comment]
@SuperDumbTM - Looking at the features we use, we don't support any post 117.0.2045.60 specific apis so it should be ok. I have pushed up a commit to better handle the EnvironmetCompleted callback. Could you please try that? Thanks.

**Comment by Snshadow** [comment]
According to the change from https://github.com/wailsapp/go-webview2/compare/v1.0.13...v1.0.14, the change has been made for MoveFocus to use a pointer for a reason from using a enum value itself.
However, when looking at the [api specification](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.movefocus?view=webview2-dotnet-1.0.2849.39#microsoft-web-webview2-core-corewebview2controller-movefocus(microsoft-web-webview2-core-corewebview2movefocusreason)), looks like it needs to take a enum value itself, however versions later then v1.0.13 would call
```
MoveFocus(pointer value of a value) 
```
instead of
```
MoveFocus(0~2)
```
as in the [enum specification](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2movefocusreason?view=webview2-dotnet-1.0.2849.39). I think that this would be the cause of the crash as it would cause an error like [this](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3059#issuecomment-1696983633), and maybe the version later then 118 has a way to avoid the crash for the failure.

What bug did this fix resolve?

**Comment by leaanthony** [comment]
Good catch! Yeah, this may have been done in error. It was a while back now so no idea why. I've reverted the commit. If you use the replace directive and use `github.com/wailsapp/go-webview2@e53758943f0fbd774dcc2ce5229cd1d082308cca` and let me know if that fixes it 🙏

**Comment by Snshadow** [comment]
@leaanthony Reverting the commit indeed fixes the crash when changing the focus for me. @SuperDumbTM, @xiexul could you check is this fixes the issue too?

**Comment by leaanthony** [comment]
I've released v1.0.18 with this revert in it. Currently pushing dep changes to Wails.

**Comment by SuperDumbTM** [comment]
I will test within this day or two, thank you all your effort!

**Comment by xiexul** [comment]
Perfect！ I used the `1.0.18` of `go-webview2` to test my application. The function can be used normally. The case test passes. Thank you for your unremitting efforts @SuperDumbTM @Snshadow

**Comment by SuperDumbTM** [comment]
I can also confirm that the latest commit did fix the crash 👏.

**Comment by leaanthony** [comment]
Thanks to you all!
